# Generated by Django 3.2.8 on 2021-11-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='lv',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
